export const ORDER_STATUSES = [
  "pending",
  "cutting",
  "stitching",
  "ready",
  "delivered",
  "canceled",
];


export const COUNTRY_CODES = [
  { code: "+93", iso: "af", name: "Afghanistan", length: 9 },
  { code: "+374", iso: "am", name: "Armenia", length: 8 },
  { code: "+994", iso: "az", name: "Azerbaijan", length: 9 },
  { code: "+973", iso: "bh", name: "Bahrain", length: 8 },
  { code: "+880", iso: "bd", name: "Bangladesh", length: 10 },
  { code: "+975", iso: "bt", name: "Bhutan", length: 8 },
  { code: "+673", iso: "bn", name: "Brunei", length: 7 },
  { code: "+855", iso: "kh", name: "Cambodia", length: 9 },
  { code: "+86", iso: "cn", name: "China", length: 11 },
  { code: "+357", iso: "cy", name: "Cyprus", length: 8 },
  { code: "+995", iso: "ge", name: "Georgia", length: 9 },
  { code: "+91", iso: "in", name: "India", length: 10 },
  { code: "+62", iso: "id", name: "Indonesia", length: 10 },
  { code: "+98", iso: "ir", name: "Iran", length: 10 },
  { code: "+964", iso: "iq", name: "Iraq", length: 10 },
  { code: "+972", iso: "il", name: "Israel", length: 9 },
  { code: "+81", iso: "jp", name: "Japan", length: 10 },
  { code: "+962", iso: "jo", name: "Jordan", length: 9 },
  { code: "+7", iso: "kz", name: "Kazakhstan", length: 10 },
  { code: "+965", iso: "kw", name: "Kuwait", length: 8 },
  { code: "+996", iso: "kg", name: "Kyrgyzstan", length: 9 },
  { code: "+856", iso: "la", name: "Laos", length: 9 },
  { code: "+961", iso: "lb", name: "Lebanon", length: 8 },
  { code: "+60", iso: "my", name: "Malaysia", length: 9 },
  { code: "+960", iso: "mv", name: "Maldives", length: 7 },
  { code: "+976", iso: "mn", name: "Mongolia", length: 8 },
  { code: "+95", iso: "mm", name: "Myanmar", length: 9 },
  { code: "+977", iso: "np", name: "Nepal", length: 10 },
  { code: "+850", iso: "kp", name: "North Korea", length: 10 },
  { code: "+968", iso: "om", name: "Oman", length: 8 },
  { code: "+92", iso: "pk", name: "Pakistan", length: 10 },
  { code: "+63", iso: "ph", name: "Philippines", length: 10 },
  { code: "+974", iso: "qa", name: "Qatar", length: 8 },
  { code: "+966", iso: "sa", name: "Saudi Arabia", length: 9 },
  { code: "+65", iso: "sg", name: "Singapore", length: 8 },
  { code: "+82", iso: "kr", name: "South Korea", length: 10 },
  { code: "+94", iso: "lk", name: "Sri Lanka", length: 9 },
  { code: "+963", iso: "sy", name: "Syria", length: 9 },
  { code: "+886", iso: "tw", name: "Taiwan", length: 9 },
  { code: "+992", iso: "tj", name: "Tajikistan", length: 9 },
  { code: "+66", iso: "th", name: "Thailand", length: 9 },
  { code: "+670", iso: "tl", name: "Timor-Leste", length: 7 },
  { code: "+90", iso: "tr", name: "Turkey", length: 10 },
  { code: "+993", iso: "tm", name: "Turkmenistan", length: 8 },
  { code: "+971", iso: "ae", name: "UAE", length: 9 },
  { code: "+998", iso: "uz", name: "Uzbekistan", length: 9 },
  { code: "+84", iso: "vn", name: "Vietnam", length: 9 },
  { code: "+967", iso: "ye", name: "Yemen", length: 9 }
];

export const STATUS_BADGE = {
  pending: "bg-amber-100 text-amber-900 ring-amber-200",
  cutting: "bg-sky-100 text-sky-900 ring-sky-200",
  stitching: "bg-violet-100 text-violet-900 ring-violet-200",
  ready: "bg-emerald-100 text-emerald-900 ring-emerald-200",
  delivered: "bg-zinc-100 text-zinc-700 ring-zinc-200",
};

/** Hex colors for Recharts (pie / legend) */
export const STATUS_CHART_COLORS = {
  pending: "#f59e0b",
  cutting: "#0ea5e9",
  stitching: "#8b5cf6",
  ready: "#10b981",
  delivered: "#71717a",
};
